# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c202359566d70ca33d0cb15945696ac666ebfa5c4ce218e858b6c410393272d5a95d7d9e986acc1f616a2b223577656c2a40d9c4020728b50a61199a21076844

test:
  secret_key_base: b841d93b7794bbbe9774c0cac545f9ce79727c4cab4818b5c08c1a58d53dbda26289d6aafb200e2da16227855e48ff7f4cd9fb229dec12106c5ffd17314eb7c2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
